[package]
name = "epubimg"
version = "0.1.0"
authors = ["rot1024 <aayhrot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.6"
clap = "3.0.0-beta.1"
regex = "1.3.9"
lazy_static = "1.4.0"
